### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Kimball1** [DemoXinMC/MoreEnchants#5]
So the Server keeps crashing when someone hits many mobs fast.
For example standing at a Skeleton Spawner. First it was only Client crashes from time to time, now the hole server crashes.

im no expert but the crash report looks to me as if it crashes everytime a Charm would´ve dropped. Besides, noone got a charm yet.

crash report : 

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 7/17/14 7:56 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at com.demoxin.minecraft.moreenchants.Item_Charm.HandleDrop(Item_Charm.java:131)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_85_Item_Charm_HandleDrop_LivingDropsEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:296)
    at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1058)
    at net.minecraft.entity.monster.EntitySkeleton.func_70645_a(EntitySkeleton.java:188)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:975)
    at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71)
    at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:313)
    at net.minecraft.world.World.func_72866_a(World.java:2605)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:841)
    at net.minecraft.world.World.func_72870_g(World.java:2559)
    at net.minecraft.world.World.func_72939_s(World.java:2383)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:672)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.demoxin.minecraft.moreenchants.Item_Charm.HandleDrop(Item_Charm.java:131)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_85_Item_Charm_HandleDrop_LivingDropsEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:296)
    at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1058)
    at net.minecraft.entity.monster.EntitySkeleton.func_70645_a(EntitySkeleton.java:188)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:975)
    at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71)
    at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:313)
    at net.minecraft.world.World.func_72866_a(World.java:2605)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:841)
    at net.minecraft.world.World.func_72870_g(World.java:2559)

-- Entity being ticked --
Details:
    Entity Type: Arrow (net.minecraft.entity.projectile.EntityArrow)
    Entity ID: 189927
    Entity Name: arrow
    Entity's Exact location: -1390.73, 64.32, -1338.38
    Entity's Block location: World: (-1391,64,-1339), Chunk: (at 1,4,5 in -87,-84; contains blocks -1392,0,-1344 to -1377,255,-1329), Region: (-3,-3; contains chunks -96,-96 to -65,-65, blocks -1536,0,-1536 to -1025,255,-1025)
    Entity's Momentum: -0.19, -0.43, -2.52
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2383)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:672)

-- Affected level --
Details:
    Level name: world
    All players: 3 total; [EntityPlayerMP['Bryler88'/119433, l='world', x=-117.63, y=64.00, z=-2608.50](Bryler88 at -117.62573149473332,64.0,-2608.498989327647), EntityPlayerMP['GodlikeLoOser'/172370, l='world', x=-1387.76, y=63.00, z=-1294.47](GodlikeLoOser at -1387.757918369004,63.0,-1294.4717401170112), EntityPlayerMP['Ghostiii869'/189532, l='world', x=-1597.76, y=30.00, z=-1116.68](Ghostiii869 at -1597.762499988079,30.0,-1116.6810900152486)]
    Chunk stats: ServerChunkCache: 1697 Drop: 0
    Level seed: 3726636144809162667
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-2,76,200), Chunk: (at 14,4,8 in -1,12; contains blocks -16,0,192 to -1,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 11965648 game time, 14375002 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 100204 (now: false), thunder time: 47577 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows Server 2008 R2 (amd64) version 6.1
    Java Version: 1.7.0, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 166501736 bytes (158 MB) / 778108928 bytes (742 MB) up to 2863333376 bytes (2730 MB)
    JVM Flags: 2 total; -XX:MaxPermSize=256m -Xmx3072M
    AABB Pool Size: 22547 (1262632 bytes; 1 MB) allocated, 17147 (960232 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.03 FML v7.2.217.1147 Minecraft Forge 10.12.2.1147 21 mods loaded, 21 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.2.217.1147} [Forge Mod Loader](minecraft_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.12.2.1147} [Minecraft Forge](minecraft_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.2.12} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.2.29} [Not Enough Items](NotEnoughItems-1.7.2-1.0.2.29-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BattleTowers{1.4.7} [Battle Towers](BattleTowers-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    betterstorage{0.9.1.105-dev} [BetterStorage](BetterStorage-1.7.2-0.9.1.105-dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    blocklings{1.1.2} [Blocklings](Blocklings-v1.1.2-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Dynmap{1.9.4.1-88} [Dynmap](Dynmap-1.9.4.1-forge-10.12.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MoreEnchants{1.3.0} [MoreEnchants](MoreEnchants-MC1.7-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NetherDungeons{1.2.1} [Nether Dungeons](NetherDungeons-1.7.2-v-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.1.0.289} [Forge Multipart](ForgeMultipart-1.7.2-1.1.0.289-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Core{4.4.4.43} [ProjectRed](ProjectRed-Base-1.7.2-4.4.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Integration{4.4.4.43} [ProjectRed-Integration](ProjectRed-Integration-1.7.2-4.4.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transmission{4.4.4.43} [ProjectRed-Transmission](ProjectRed-Integration-1.7.2-4.4.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Expansion{4.4.4.43} [ProjectRed-Expansion](ProjectRed-Mechanical-1.7.2-4.4.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transportation{4.4.4.43} [ProjectRed-Transportation](ProjectRed-Mechanical-1.7.2-4.4.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.2_1.7.2} [Waila](Waila-1.5.2a_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.1.0.289} [Minecraft Multipart Plugin](ForgeMultipart-1.7.2-1.1.0.289-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.1.0.289} [Forge Microblocks](ForgeMultipart-1.7.2-1.1.0.289-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1651 (92456 bytes; 0 MB) allocated, 1183 (66248 bytes; 0 MB) used
    Player Count: 3 / 20; [EntityPlayerMP['Bryler88'/119433, l='world', x=-117.63, y=64.00, z=-2608.50](Bryler88 at -117.62573149473332,64.0,-2608.498989327647), EntityPlayerMP['GodlikeLoOser'/172370, l='world', x=-1387.76, y=63.00, z=-1294.47](GodlikeLoOser at -1387.757918369004,63.0,-1294.4717401170112), EntityPlayerMP['Ghostiii869'/189532, l='world', x=-1597.76, y=30.00, z=-1116.68](Ghostiii869 at -1597.762499988079,30.0,-1116.6810900152486)]
    Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Kimball1** [comment]
eh...bump ?

**Comment by DemoXinMC** [comment]
Fix is coming up.  I've got it fixed in the code, just haven't implemented the other parts of the update yet, but I've actually been working on this major update tonight.

**Comment by Dragynrain** [comment]
I'm still getting this error also.. Did this ever get addressed?
